import type { Account, Category } from '../types';

export const INITIAL_ACCOUNTS: Account[] = [
  { id: 'cash', name: 'CASH', type: 'cash', emoji: '💵', balance: 0 },
  { id: 'bca', name: 'BCA', type: 'bank', icon: '/icons/banks/bca.webp', balance: 0 },
  { id: 'mandiri', name: 'MANDIRI', type: 'bank', icon: '/icons/banks/mandiri.webp', balance: 0 },
  { id: 'krom', name: 'KROM', type: 'bank', icon: '/icons/banks/krom.webp', balance: 0 },
  { id: 'jago', name: 'JAGO', type: 'bank', icon: '/icons/banks/jago.webp', balance: 0 },
  { id: 'sampoerna', name: 'SAMPOERNA', type: 'bank', icon: '/icons/banks/sampoerna.webp', balance: 0 },
  { id: 'seabank', name: 'SEABANK', type: 'bank', icon: '/icons/banks/seabank.webp', balance: 0 },
  { id: 'gopay', name: 'GOPAY', type: 'ewallet', icon: '/icons/banks/gopay.webp', balance: 0 },
  { id: 'shopeepay', name: 'SHOPEEPAY', type: 'ewallet', icon: '/icons/banks/shopeepay.webp', balance: 0 },
  { id: 'dana', name: 'DANA', type: 'ewallet', icon: '/icons/banks/dana.webp', balance: 0 },
  { id: 'honest', name: 'Honest Card', type: 'credit', icon: '/icons/banks/honest.webp', balance: 0 },
  { id: 'nex', name: 'Nex Card', type: 'credit', icon: '/icons/banks/nex.webp', balance: 0 },
  { id: 'kredivo', name: 'Kredivo', type: 'credit', icon: '/icons/banks/kredivo.webp', balance: 0 },
  { id: 'spaylatter', name: 'Spaylatter', type: 'credit', icon: '/icons/banks/spaylatter.webp', balance: 0 },
  { id: 'jagoloan', name: 'Jago Loan', type: 'credit', icon: '/icons/banks/jagoloan.webp', balance: 0 },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Pengeluaran
  { id: 'makan', name: 'Makan', type: 'pengeluaran', emoji: '🍔' },
  { id: 'coffee', name: 'Coffee/Snack', type: 'pengeluaran', emoji: '☕' },
  { id: 'makanan_pokok', name: 'Makanan Pokok', type: 'pengeluaran', emoji: '🍚' },
  { id: 'minuman_pokok', name: 'Minuman Pokok', type: 'pengeluaran', emoji: '🥛' },
  { id: 'bensin', name: 'Bensin', type: 'pengeluaran', emoji: '⛽' },
  { id: 'parkir', name: 'Parkir', type: 'pengeluaran', emoji: '🅿️' },
  { id: 'service_motor', name: 'Service Motor', type: 'pengeluaran', emoji: '🏍️' },
  { id: 'kesehatan', name: 'Kesehatan/Healthcare', type: 'pengeluaran', emoji: '🏥' },
  { id: 'selfcare', name: 'Selfcare', type: 'pengeluaran', emoji: '💆' },
  { id: 'subscriptions', name: 'Subscriptions', type: 'pengeluaran', emoji: '📺' },
  { id: 'admin', name: 'Admin', type: 'pengeluaran', emoji: '💳' },
  { id: 'kitchen', name: 'Kitchen Essential', type: 'pengeluaran', emoji: '🍳' },
  { id: 'invest', name: 'Nabung/Invest', type: 'pengeluaran', emoji: '💰' },
  { id: 'listrik', name: 'Listrik', type: 'pengeluaran', emoji: '💡' },
  { id: 'wifi', name: 'WIFI', type: 'pengeluaran', emoji: '📶' },
  { id: 'internet', name: 'Internet Package', type: 'pengeluaran', emoji: '📱' },
  { id: 'laundry', name: 'Laundry', type: 'pengeluaran', emoji: '👕' },
  { id: 'toiletries', name: 'Toiletries', type: 'pengeluaran', emoji: '🧴' },
  { id: 'keluarga', name: 'Keluarga', type: 'pengeluaran', emoji: '👨‍👩‍👧' },
  { id: 'bayar_paylater', name: 'Bayar Paylatter', type: 'pengeluaran', emoji: '💳' },
  { id: 'kuliah', name: 'Kuliah', type: 'pengeluaran', emoji: '🎓' },
  { id: 'entertainment', name: 'Hobby/Entertainment', type: 'pengeluaran', emoji: '🎮' },
  { id: 'donate', name: 'Donate', type: 'pengeluaran', emoji: '❤️' },
  { id: 'kado', name: 'Kondangan/Kado', type: 'pengeluaran', emoji: '🎁' },
  { id: 'annual', name: 'Annual Expenses', type: 'pengeluaran', emoji: '📅' },
  { id: 'tak_terduga', name: 'Biaya Tak Terduga', type: 'pengeluaran', emoji: '⚠️' },
  // Pemasukan
  { id: 'gaji', name: 'Gaji', type: 'pemasukan', emoji: '💵' },
  { id: 'kembalian_hutang', name: 'Kembalian Hutang', type: 'pemasukan', emoji: '🔙' },
  { id: 'interest', name: 'Interest', type: 'pemasukan', emoji: '📈' },
  { id: 'loan', name: 'Loan', type: 'pemasukan', emoji: '🤝' },
  { id: 'cashback', name: 'Cashback', type: 'pemasukan', emoji: '💸' },
  { id: 'gift', name: 'Gift', type: 'pemasukan', emoji: '🎁' },
];
